name: fastscape-simulator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.12
  - pandas=0.20.3
  - xarray=0.9.6
  - xarray-simlab=0.1.1
  - xarray-topo=0.0.10
  - ipython
  - matplotlib
